### ISSUE TITLE
[IMPROVEMENT] Revert Clang-CL compilation workaround

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#1402]
### Describe the issue

Compilation failed for Clang-CL (https://github.com/PowerGridModel/power-grid-model/actions/runs/26138748913/attempts/1) on most recent Visual Studio version, which is also being deployed in the GitHub actions runner images (https://github.com/actions/runner-images/blob/win25-vs2026/20260518.113/images/windows/Windows2025-VS2026-Readme.md).

The root cause was a bug reported to STL in https://github.com/microsoft/STL/issues/6294  and fixed in https://github.com/microsoft/STL/pull/6298 .

A workaround was introduced in #1403 . This issue is about reverting the workaround introduced in #1403 after https://github.com/microsoft/STL/pull/6298 is released to GA as well as GitHub Actions

This issue is for tracking purposes.

**Comment by TonyXiang8787** [comment]
@mgovers  can this be closed? You already have a fix for our code base?

**Comment by mgovers** [comment]
Yes, you're right, Resolved by #1403 

But on request by @petersalemink95, let's rebrand this issue to keep track of reverting #1237 once the STL fix is merged ( https://github.com/microsoft/STL/pull/6298 ) and released
